#!/usr/bin/env python
"""
update_readme_status.py — regenerate the status tables in README.md by COUNTING FILES.

README.md says of its own status table:

    "This table is the honest state of the repo — check it before assuming a file exists.
     It is regenerated by counting files rather than from memory, so when it and a module
     description disagree, the table is right."

That claim is only true if something actually regenerates it. Nothing did, and the table
drifted: it reported CS-13 at 2,918 lines when the file had grown to 2,977, and it listed
nine interview banks as missing that existed by the time anyone read it. A status table
that is wrong in the direction of "less finished than it is" wastes an author's afternoon
rewriting a file that is already there; wrong in the other direction, it ships a hole.

This script derives every cell from the filesystem, so a stale table becomes impossible —
run it after adding or editing any module artefact.

Usage
-----
    python tools/update_readme_status.py            # rewrite README.md in place
    python tools/update_readme_status.py --check    # exit 1 if README.md is stale (CI)
    python tools/update_readme_status.py --print    # show the table, change nothing

The module titles come from MODULES below rather than from the filenames, because the
filenames are abbreviated and the README's titles are the reader-facing names. If you
rename a module, change it here AND in the README heading — this script only owns the
table rows.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# The status glyphs (✅ ⬜) are unencodable in a cp1252 console, which is the Windows
# default — `--print` would die on its first line with a UnicodeEncodeError while the
# logic was perfectly fine. Same fix as code/common/_console.py; inlined rather than
# imported because tools/ is a sibling of code/ and a cross-directory import would break
# if either moves.
for _stream in (sys.stdout, sys.stderr):
    if (getattr(_stream, "encoding", "") or "").lower().replace("-", "") not in ("utf8", "utf8mb4"):
        try:
            _stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError, OSError):
            pass

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# id -> (title, part). `part` groups the rows under the README's existing headings.
MODULES: dict[int, tuple[str, int]] = {
    1:  ("Foundations: Pretraining and Training", 1),
    2:  ("Transfer Learning and Fine-Tuning", 1),
    3:  ("The Fine-Tuning Framework Landscape", 1),
    4:  ("Fine-Tuning vs RAG vs Agents", 1),
    5:  ("From RNN/LSTM to Attention", 1),
    6:  ("The Hugging Face Masterclass", 1),
    7:  ("BERT Fine-Tuning (classification, NER)", 2),
    8:  ("Knowledge Distillation: Foundations", 2),
    9:  ("Distillation: LLM → SLM", 2),
    10: ("Quantization I: PTQ, QAT, the theory", 2),
    11: ("Quantization II: GPTQ, AWQ, GGUF", 2),
    12: ("Domain-Adaptive Continued Pretraining", 2),
    13: ("Instruction Fine-Tuning (SFT)", 3),
    14: ("The Alignment Map: RLHF, PPO, DPO, ORPO", 3),
    15: ("LLaMA-Factory: no-code fine-tuning", 3),
    16: ("Unsloth: 2–4× faster, low-VRAM", 4),
    17: ("Axolotl: YAML-driven training", 4),
    18: ("OpenAI GPT fine-tuning", 4),
    19: ("Gemini / Vertex AI fine-tuning", 4),
    20: ("Fine-Tuning Small Language Models", 5),
    21: ("Multimodal / Vision-Language", 5),
    22: ("Embedding Models and Embedding FT", 5),
    23: ("LoRA & QLoRA: the PEFT deep dive", 5),
    24: ("RL Fundamentals & RLHF with PPO", 6),
    25: ("DPO — Direct Preference Optimization", 6),
    26: ("GRPO — Group Relative Policy Optimization", 6),
    27: ("ORPO — Odds Ratio Preference Optimization", 6),
    28: ("Capstone: the end-to-end pipeline", 6),
}

PART_HEADINGS = {
    1: "### Part I — Foundations (CS-01 … CS-06)",
    2: "### Part II — Compression and Domain Adaptation (CS-07 … CS-12)",
    3: "### Part III — The Alignment Stack (CS-13 … CS-15)",
    4: "### Part IV — Tooling and Platforms (CS-16 … CS-19)",
    5: "### Part V — Modalities and Scale (CS-20 … CS-23)",
    6: "### Part VI — Preference Optimisation, in Depth (CS-24 … CS-28)",
}

TABLE_HEADER = "| # | Module | Case study | IQ | Cheat sheet |\n|---|---|---|---|---|"

MISSING = "⬜"


def line_count(path: Path) -> int:
    """Count lines the way `wc -l` does — number of newline characters.

    Not `len(f.read_text().splitlines())`, which counts a final unterminated line as a
    line and so disagrees with `wc -l` by one on every file that lacks a trailing newline.
    The README's numbers were originally taken with `wc -l`; matching it keeps the diff
    honest when this script replaces them.
    """
    n = 0
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            n += chunk.count(b"\n")
    return n


def find_artifact(kind: str, num: int) -> Path | None:
    """`kind` is a directory name. Match on the numeric id, not on the title.

    Titles differ between the filename and the README (abbreviations, em-dashes, a slash
    in "Gemini / Vertex"), so title matching fails exactly when a title is edited. The id
    is the stable key.
    """
    hits = sorted((ROOT / kind).glob(f"*{num:02d}-*.md"))
    hits = [h for h in hits if re.match(rf"^[A-Z]{{2}}-{num:02d}-", h.name)]
    if len(hits) > 1:
        sys.exit(f"  {kind}: {len(hits)} files match module {num:02d}: "
                 f"{[h.name for h in hits]}. Remove the duplicate.")
    return hits[0] if hits else None


def cell(path: Path | None) -> str:
    return f"✅ {line_count(path)}" if path else MISSING


def build_tables() -> str:
    out: list[str] = []
    for part, heading in PART_HEADINGS.items():
        out.append(heading)
        if part == 3:
            # The README asserts this part is complete. Deriving the claim means the
            # assertion cannot survive a module going missing.
            complete = all(
                find_artifact(k, n) is not None
                for n, (_, p) in MODULES.items() if p == 3
                for k in ("case-studies", "interview-questions", "cheat-sheets")
            )
            if complete:
                out.append("**Complete** — every module has all three artifacts.")
        out.append("")
        out.append(TABLE_HEADER)
        for n, (title, p) in MODULES.items():
            if p != part:
                continue
            out.append(f"| {n:02d} | {title} | "
                       f"{cell(find_artifact('case-studies', n))} | "
                       f"{cell(find_artifact('interview-questions', n))} | "
                       f"{cell(find_artifact('cheat-sheets', n))} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def counts() -> dict[str, str]:
    cs = list((ROOT / "case-studies").glob("*.md"))
    iq = list((ROOT / "interview-questions").glob("*.md"))
    ch = list((ROOT / "cheat-sheets").glob("*.md"))
    ap = list((ROOT / "appendices").glob("*.md"))
    total_cs = sum(line_count(p) for p in cs)
    return {
        "case studies": f"{len(cs)} / {len(MODULES)}",
        "interview banks": f"{len(iq)} / {len(MODULES)}",
        "cheat sheets": f"{len(ch)} / {len(MODULES)}",
        "appendices": f"{len(ap)} / 1",
        "cs_lines": f"{total_cs:,}",
        "iq_q": "",  # filled by caller if it wants to count questions
    }


def missing_list(kind: str) -> str:
    ids = [f"{kind}-{n:02d}" for n in MODULES if find_artifact(
        {"CS": "case-studies", "IQ": "interview-questions", "CH": "cheat-sheets"}[kind], n) is None]
    return ", ".join(ids) if ids else "—"


def build_progress() -> str:
    ap = list((ROOT / "appendices").glob("*.md"))
    cs = list((ROOT / "case-studies").glob("*.md"))
    iq = list((ROOT / "interview-questions").glob("*.md"))
    ch = list((ROOT / "cheat-sheets").glob("*.md"))
    total_cs = sum(line_count(p) for p in cs)

    # The Notes column carries the per-artifact convention rather than a count, because the
    # count is already in the Written column and a duplicated number is a number that can
    # disagree with itself.
    rows = [
        ("Case studies", len(cs), len(MODULES), missing_list("CS"),
         f"{total_cs:,} lines total; house structure is §0–§20 plus two appendices"),
        ("Interview banks", len(iq), len(MODULES), missing_list("IQ"),
         "question + model answer + what the interviewer is testing"),
        ("Cheat sheets", len(ch), len(MODULES), missing_list("CH"),
         "13-section condensed format, cross-linked to the case study"),
        ("Appendices", len(ap), 1, "—" if ap else "AP-01",
         "bridges between the technical modules and their context"),
    ]
    out = ["| | Written | Missing | Notes |", "|---|---|---|---|"]
    for name, n, total, miss, note in rows:
        out.append(f"| {name} | {n} / {total} | {miss} | {note} |")
    out.append("")
    out.append("These counts are generated by `tools/update_readme_status.py`, which derives "
               "every cell from the filesystem. Run it after adding or editing an artifact; "
               "`--check` exits non-zero if this block is stale.")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="Exit 1 if README.md does not match the filesystem.")
    ap.add_argument("--print", dest="show", action="store_true",
                    help="Print the generated tables without touching README.md.")
    a = ap.parse_args()

    tables = build_tables()
    progress = build_progress()

    if a.show:
        print(tables)
        print(progress)
        return

    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")

    # Replace the block from the first Part heading to the end of the Part VI table.
    start = text.find(PART_HEADINGS[1])
    if start == -1:
        sys.exit(f"  Could not find {PART_HEADINGS[1]!r} in README.md. "
                 f"The table anchor moved; update PART_HEADINGS.")
    end_marker = "\n**Legend:**"
    end = text.find(end_marker, start)
    if end == -1:
        sys.exit("  Could not find the '**Legend:**' line that terminates the status block.")

    new = text[:start] + tables + text[end:]

    # Replace the progress table, anchored on its own heading.
    pstart = new.find("**Progress by artifact type:**")
    if pstart != -1:
        pend = new.find("\n---", pstart)
        if pend == -1:
            sys.exit("  Found the progress heading but no terminating '---'.")
        new = new[:pstart] + "**Progress by artifact type:**\n\n" + progress + "\n" + new[pend:]

    if new == text:
        print("  README.md status tables are already current.")
        return
    if a.check:
        sys.exit("  README.md is STALE. Run: python tools/update_readme_status.py")
    readme.write_text(new, encoding="utf-8")
    print(f"  README.md updated ({len(text):,} -> {len(new):,} bytes).")


if __name__ == "__main__":
    main()
